plugins:
  tz_approval_enabled:
    default: true
    client: true

  tz_approval_binding_mode:
    type: enum
    default: "tag"
    choices:
      - tag
      - category
    client: true

  tz_approval_tags:
    type: list
    default: "тех-задание"
    client: true

  tz_approval_allowed_groups:
    type: group_list
    default: ""

  tz_approval_categories:
    type: category_list
    default: ""

  tz_author_approval_delay:
    type: integer
    default: 600
    min: 0

  tz_approval_light_color:
    type: string
    default: "#d9a441"
    client: true

  tz_approval_dark_color:
    type: string
    default: "#d9a441"
    client: true

  tz_approval_icon:
    type: icon
    default: "file-signature"
    client: true

  tz_approval_status_token:
    type: string
    default: ""
